const questions = [
  // ── WEEK 1 ──
  { id: 1, week: 1, question: "What is the primary goal of Human-Computer Interaction (HCI)?", options: ["Improve computer hardware", "Make interaction effective, efficient, and satisfying", "Reduce data usage", "Teach programming"], answer: 1 },
  { id: 2, week: 1, question: "Which example represents bad design?", options: ["A door with a clear push/pull label", "A TV remote with too many buttons", "A phone with customizable themes", "A book with a table of contents"], answer: 1 },
  { id: 3, week: 1, question: "Usability mainly describes:", options: ["App color scheme", "How easily users achieve their goals", "Internet speed", "Type of hardware"], answer: 1 },
  { id: 4, week: 1, question: "Which of the following is an interactive system?", options: ["Printed map", "Digital ATM touch interface", "Wall poster", "Paper calendar"], answer: 1 },
  { id: 5, week: 1, question: "Why is understanding user needs important in user-centered design?", options: ["To reduce app cost", "To match designs with real user behaviors", "To create fancy animations", "To increase marketing budget"], answer: 1 },
  { id: 6, week: 1, question: "Why is a door without signifiers (push/pull marks) confusing?", options: ["It has too much color", "It uses expensive material", "Its affordance and signifiers are unclear", "It is automatic"], answer: 2 },
  { id: 7, week: 1, question: "What makes a TV remote with many buttons a poor design example?", options: ["It is heavy", "Battery drains quickly", "Cognitive overload and poor usability", "It is not colorful"], answer: 2 },
  { id: 8, week: 1, question: "Which step in user-centered design involves understanding user challenges and context?", options: ["Advertising", "Deployment", "User research", "Coding"], answer: 2 },
  { id: 9, week: 1, question: "Which HCI principle was violated in the Boeing 737 MAX case?", options: ["Too many UI colors", "No touchscreen support", "Lack of visibility and poor feedback for automation", "Icons were too small"], answer: 2 },
  { id: 10, week: 1, question: "Which concept explains why users make errors when controls do not match their mental model?", options: ["Animation design", "Aesthetic layout", "Mental models and signifiers", "Download speed"], answer: 2 },

  // ── WEEK 2 ──
  { id: 11, week: 2, question: "According to Henry Dreyfuss's idea of design, when does a designer succeed?", options: ["When the product uses the latest technology", "When users feel comfortable and can use the product without friction", "When the product is inexpensive", "When the product looks stylish"], answer: 1 },
  { id: 12, week: 2, question: "What was a major reason for the commercial failure of Google Glass?", options: ["No camera support", "Privacy concerns and awkward design", "Low screen brightness", "Lack of wireless connectivity"], answer: 1 },
  { id: 13, week: 2, question: "What is the first step in deciding what to design?", options: ["Finalizing the brand logo", "Identifying who the users are", "Choosing color schemes", "Deciding the marketing plan"], answer: 1 },
  { id: 14, week: 2, question: "What is the main goal of interaction design according to Sharp, Rogers, and Preece?", options: ["Supporting communication and interaction in daily life", "Reducing manufacturing costs", "Increasing screen brightness", "Designing for entertainment"], answer: 0 },
  { id: 15, week: 2, question: "Which of the following best represents User Experience (UX)?", options: ["How users feel emotionally while using the product", "The processor speed of a device", "Only the visual layout", "The number of features in an app"], answer: 0 },
  { id: 16, week: 2, question: "Why are multidisciplinary teams valuable in interaction design?", options: ["They reduce the cost of development", "They make meetings shorter", "They generate diverse ideas and perspectives", "They eliminate the need for user testing"], answer: 2 },
  { id: 17, week: 2, question: "What is inclusivity in design?", options: ["Making interfaces look colorful", "Designing products for diverse user needs and backgrounds", "Removing advanced features", "Designing only for expert users"], answer: 1 },
  { id: 18, week: 2, question: "What is accessibility mainly focused on?", options: ["Increasing entertainment content", "Improving device speed", "Making products usable by people with disabilities", "Reducing UI animations"], answer: 2 },
  { id: 19, week: 2, question: "Which design principle ensures that crucial functions are easy to locate?", options: ["Memorability", "Flexibility", "Aesthetics", "Visibility"], answer: 3 },
  { id: 20, week: 2, question: "What is affordance in design?", options: ["The cost of the product", "Visual cues that indicate how an element should be used", "The brand reputation", "The color contrast ratio"], answer: 1 },

  // ── WEEK 3 ──
  { id: 21, week: 3, question: "Which stage of Design Thinking focuses on understanding the user's needs and behaviors?", options: ["Prototype", "Empathize", "Test", "Implement"], answer: 1 },
  { id: 22, week: 3, question: "The Double Diamond design process was developed by:", options: ["Apple", "Nielsen Norman Group", "UK Design Council", "Microsoft Research"], answer: 2 },
  { id: 23, week: 3, question: "Which of the following is not one of the six stages of Design Thinking?", options: ["Define", "Ideate", "Evaluate", "Empathize"], answer: 2 },
  { id: 24, week: 3, question: "In the Define stage, the key goal is to:", options: ["Sketch wireframes", "Frame the problem clearly", "Conduct A/B testing", "Create high-fidelity prototypes"], answer: 1 },
  { id: 25, week: 3, question: "Activity-centered design primarily focuses on:", options: ["User preferences", "User emotions", "Tasks and activities users perform", "Visual layout aesthetics"], answer: 2 },
  { id: 26, week: 3, question: "Which of the following is not a key component of system design?", options: ["Data Management", "Interfaces", "Memory recall", "Architecture"], answer: 2 },
  { id: 27, week: 3, question: "The Interaction Design Process emphasizes four basic activities. Which one of these is included?", options: ["Monetization", "Discovering requirements", "Branding", "Advertising"], answer: 1 },
  { id: 28, week: 3, question: "Genius design relies heavily on:", options: ["Extensive user testing", "Designer intuition and expertise", "Market surveys", "Accessibility guidelines"], answer: 1 },
  { id: 29, week: 3, question: "Which lifecycle model is based on rapid prototyping and iteration within 5 days?", options: ["Research in the Wild", "Waterfall Model", "Google Design Sprints", "Spiral Model"], answer: 2 },
  { id: 30, week: 3, question: "According to Week 3, user involvement is important because:", options: ["It helps reduce the app size", "Users can become stakeholders and contribute feedback", "It speeds up coding", "It avoids the need for iteration"], answer: 1 },

  // ── WEEK 4 ──
  { id: 31, week: 4, question: "User perspectives in HCI help designers understand:", options: ["Only the visual UI layout", "How users perceive and interact with technology", "How designers communicate with developers", "Only system requirements"], answer: 1 },
  { id: 32, week: 4, question: "Which of the following is an example of accessibility consideration?", options: ["Using bright colors only", "Providing adjustable font sizes and dyslexia-friendly modes", "Adding decorative animations", "Increasing advertisements"], answer: 1 },
  { id: 33, week: 4, question: "Novice users generally prefer:", options: ["Only voice-based interfaces", "Highly customizable and complex interfaces", "Minimal guidance and advanced shortcuts", "Simple interfaces with clear instructions"], answer: 3 },
  { id: 34, week: 4, question: "A persona is best described as:", options: ["A real user hired by the company", "A fictional, data-driven representation of a user", "A system architecture model", "A marketing campaign tool"], answer: 1 },
  { id: 35, week: 4, question: "Surveys in user research are useful because they:", options: ["Always provide emotional depth", "Allow quick collection of large-scale data", "Guarantee unbiased answers", "Replace interviews completely"], answer: 1 },
  { id: 36, week: 4, question: "Empathy mapping categorizes insights into:", options: ["Features, modules, layouts, workflows", "Says, Thinks, Does, Feels", "Inputs, outputs, processes, storage", "Goals, sub-goals, errors, feedback"], answer: 1 },
  { id: 37, week: 4, question: "A common challenge in user perspectives is:", options: ["Too many designers", "Conflicting needs among different user groups", "Unlimited research time", "Lack of design tools"], answer: 1 },
  { id: 38, week: 4, question: "Affinity mapping is mainly used to:", options: ["Assign tasks to team members", "Organize qualitative data into themes", "Remove unnecessary system features", "Design UI wireframes"], answer: 1 },
  { id: 39, week: 4, question: "A POV (Point of View) statement includes:", options: ["System hardware requirements", "User, need, and insight", "UI color preferences", "Coding-level issues"], answer: 1 },
  { id: 40, week: 4, question: "Data clustering helps in:", options: ["Grouping users based on similar behaviors", "Randomly distributing users", "Increasing device performance", "Removing prototypes"], answer: 0 },

  // ── WEEK 5 ──
  { id: 41, week: 5, question: "Which of the following best describes a conceptual model?", options: ["A detailed UI layout", "A mental representation of how a system works", "A list of system requirements", "A coding guideline document"], answer: 1 },
  { id: 42, week: 5, question: "What is an example of an assumption in interface design?", options: ["Testing a prototype with users", "Taking something for granted without evidence", "Mapping user journeys", "Writing code before wireframes"], answer: 1 },
  { id: 43, week: 5, question: "Which component is commonly used in online shopping conceptual models?", options: ["Homepage wallpaper", "Shopping cart", "Video playback controls", "Battery indicator"], answer: 1 },
  { id: 44, week: 5, question: "Interface metaphors help users by:", options: ["Making systems slower", "Increasing hardware complexity", "Leveraging familiarity for learning new systems", "Removing the need for feedback"], answer: 2 },
  { id: 45, week: 5, question: "Which cognitive principle states that decision time increases with more choices?", options: ["Miller's Law", "Fitts's Law", "Hick's Law", "Gestalt Law of Proximity"], answer: 2 },
  { id: 46, week: 5, question: "What is the purpose of a system image?", options: ["To describe internal code structure", "To show how the system actually works through the interface", "To explain marketing strategy", "To define business revenue"], answer: 1 },
  { id: 47, week: 5, question: "Which of the following is a drawback of interface metaphors?", options: ["They always reduce cognitive load", "They break all cultural norms", "They may limit designers' creativity", "They remove the need for conceptual models"], answer: 2 },
  { id: 48, week: 5, question: "Cognitive load increases when:", options: ["Interfaces use familiar patterns", "Users see excessive irrelevant information", "Steps are minimized", "Icons are consistent"], answer: 1 },
  { id: 49, week: 5, question: "Which cognitive aspect focuses on how users perceive visual elements?", options: ["Decision-making", "Perception", "Problem-solving", "Reflective cognition"], answer: 1 },
  { id: 50, week: 5, question: "Which emerging trend in interfaces directly uses the human brain for input?", options: ["AR overlays", "Voice interaction", "Brain–Computer Interfaces", "Card-based UI"], answer: 2 },

  // ── WEEK 6 ──
  { id: 51, week: 6, question: "What is the primary purpose of identifying data requirements in HCI?", options: ["To create marketing campaigns", "To determine what information is needed to inform design decisions", "To reduce memory usage in applications", "To choose programming languages"], answer: 1 },
  { id: 52, week: 6, question: "Which type of data includes demographics and user preferences?", options: ["System data", "User data", "Context data", "Task data"], answer: 1 },
  { id: 53, week: 6, question: "Which of the following is a qualitative data-gathering technique?", options: ["Analytics logs", "Surveys with multiple-choice questions", "User interviews", "System performance metrics"], answer: 2 },
  { id: 54, week: 6, question: "Crowdsourcing in HCI is mainly beneficial because:", options: ["It reduces the need for user testing", "It gathers data from diverse and large populations", "It guarantees unbiased data automatically", "It eliminates qualitative research"], answer: 1 },
  { id: 55, week: 6, question: "Fairness in data collection ensures that:", options: ["All users are treated equitably in data and algorithms", "The system runs faster", "Participants cannot withdraw", "Only expert users are included"], answer: 0 },
  { id: 56, week: 6, question: "Field studies involve:", options: ["Observing users in controlled lab settings", "Recording system logs only", "Observing users in their natural environment", "Removing outliers from datasets"], answer: 2 },
  { id: 57, week: 6, question: "Which tool is commonly used for real-time data handling?", options: ["Tableau", "Firebase", "NVivo", "SPSS"], answer: 1 },
  { id: 58, week: 6, question: "Which of the following is a key issue in data ethics?", options: ["Increasing app performance", "User interface color selection", "Transparency in how data is collected and used", "Adding more user features"], answer: 2 },
  { id: 59, week: 6, question: "Inter-Annotator Agreement (IAA) is used to:", options: ["Visualize data using graphs", "Measure consistency among multiple annotators", "Improve system performance", "Replace manual labeling"], answer: 1 },
  { id: 60, week: 6, question: "Which statistical method is used to find relationships between variables?", options: ["Affinity mapping", "Regression analysis", "Unstructured interviewing", "Card sorting"], answer: 1 },

  // ── WEEK 7 ──
  { id: 61, week: 7, question: "What is a prototype in interaction design?", options: ["A finalized product", "A manifestation of a design that stakeholders can interact with", "Only a software demo", "A marketing document"], answer: 1 },
  { id: 62, week: 7, question: "Which of the following is an example of Lo-Fi prototyping?", options: ["Pixel-perfect UI", "Paper sketches", "Fully interactive app", "High-resolution mockup"], answer: 1 },
  { id: 63, week: 7, question: "Storyboards in prototyping help designers by:", options: ["Writing code automatically", "Breaking user tasks into scenes to visualize interaction", "Generating analytics", "Creating animations for UI"], answer: 1 },
  { id: 64, week: 7, question: "Which prototyping type provides broad coverage with low detail?", options: ["Vertical", "Horizontal", "Hi-Fi", "Wizard-of-Oz"], answer: 1 },
  { id: 65, week: 7, question: "Mid-Fidelity prototypes typically include:", options: ["Stick figures only", "Grayscale wireframes with limited interactions", "Pixel-perfect color UI", "Final design animations"], answer: 1 },
  { id: 66, week: 7, question: "Smart UI refers to interfaces that:", options: ["Are built only with code", "Use AI to adapt to user behavior and context", "Do not require user data", "Never personalize content"], answer: 1 },
  { id: 67, week: 7, question: "Which is an advantage of Smart UI?", options: ["Random interface behavior", "Personalized and adaptive user experience", "Increased manual effort for users", "No support for accessibility"], answer: 1 },
  { id: 68, week: 7, question: "Wizard-of-Oz prototyping involves:", options: ["A human simulating system responses behind the scenes", "Full autonomous system", "Physical hardware testing", "Running A/B experiments"], answer: 0 },
  { id: 69, week: 7, question: "Vertical prototyping focuses on:", options: ["A wide range of features with little detail", "A detailed exploration of a single feature", "Creating only animations", "Testing final UI only"], answer: 1 },
  { id: 70, week: 7, question: "Which tool is commonly used for mid or high-fidelity UI prototypes?", options: ["Sticky notes", "Figma", "Lego blocks", "Scenarios only"], answer: 1 },

  // ── WEEK 8 ──
  { id: 71, week: 8, question: "What is the main purpose of evaluation in HCI?", options: ["To increase hardware performance", "To assess usability, effectiveness, and user experience", "To test marketing strategies", "To reduce development cost"], answer: 1 },
  { id: 72, week: 8, question: "Which type of evaluation occurs during the design process to refine the product?", options: ["Summative", "Diagnostic", "Formative", "Longitudinal"], answer: 2 },
  { id: 73, week: 8, question: "Usability testing primarily involves:", options: ["Experts reviewing code", "Observing real users performing tasks", "Only collecting analytics", "Replacing prototypes with final UI"], answer: 1 },
  { id: 74, week: 8, question: "Which evaluation method requires evaluators to simulate user behavior step-by-step?", options: ["Heuristic Evaluation", "Cognitive Walkthrough", "A/B Testing", "Eye Tracking"], answer: 1 },
  { id: 75, week: 8, question: "In experiment design, which approach assigns different groups to different conditions?", options: ["Within-subjects", "Mixed methods", "Between-subjects", "Triangulated testing"], answer: 2 },
  { id: 76, week: 8, question: "Which metric measures how fast users complete a task?", options: ["Error severity", "Task success rate", "Time on task", "Net Promoter Score"], answer: 2 },
  { id: 77, week: 8, question: "Eye tracking helps evaluators understand:", options: ["System load time", "Where users focus attention on the interface", "User emotions only", "The number of app downloads"], answer: 1 },
  { id: 78, week: 8, question: "Which principle ensures that participants voluntarily agree to evaluation?", options: ["Counterbalancing", "Informed consent", "Aesthetic consistency", "Reliability"], answer: 1 },
  { id: 79, week: 8, question: "Which evaluation method is cost-effective and identifies issues early using established principles?", options: ["A/B Testing", "Heuristic Evaluation", "Biometric Metrics", "Field Studies"], answer: 1 },
  { id: 80, week: 8, question: "Which predictive model estimates pointing time based on movement distance and target size?", options: ["Hick's Law", "Mental Model", "Cognitive Load Theory", "Fitts's Law"], answer: 3 },

  // ── WEEK 9 ──
  { id: 81, week: 9, question: "IoT refers to:", options: ["A network of physical objects with sensors and connectivity", "Devices that store only offline data", "Tools without any automation", "Only entertainment systems"], answer: 0 },
  { id: 82, week: 9, question: "The main goal of IoT is:", options: ["To increase device size", "To \"connect the unconnected\"", "To remove automation from homes", "To limit wireless technology"], answer: 1 },
  { id: 83, week: 9, question: "Which example shows HCI + IoT interaction?", options: ["A robotic arm running without feedback", "Users controlling smart bulbs via a mobile app", "Devices interacting only through printed manuals", "A non-digital clock"], answer: 1 },
  { id: 84, week: 9, question: "Which interaction modalities are common in IoT?", options: ["Voice, gesture, and touch", "Only handwritten input", "Only QR-code scanning", "Only mechanical switches"], answer: 0 },
  { id: 85, week: 9, question: "A major HCI challenge in IoT is:", options: ["Increasing UI colors", "Achieving consistent interaction across many devices", "Ensuring devices always remain offline", "Removing all system notifications"], answer: 1 },
  { id: 86, week: 9, question: "Why is HCI crucial in IoT systems?", options: ["It hides system feedback", "It ensures usability and intuitive interaction across devices", "It prevents real-time interaction", "It forces users to follow only one workflow"], answer: 1 },
  { id: 87, week: 9, question: "HaptiDrag creates friction using:", options: ["Heated plates", "Ultrasonic vibrations", "Electroadhesion technology", "Physical wheels"], answer: 2 },
  { id: 88, week: 9, question: "HaptiDrag enhances VR by:", options: ["Giving realistic tactile feedback with variable friction", "Removing haptic sensations", "Reducing VR stability", "Removing all gestures"], answer: 0 },
  { id: 89, week: 9, question: "MobiTangibles supports VR tool training by:", options: ["Tracking small tool movements using smartphone magnetometers", "Using heat sensors only", "Removing all sensors", "Replacing tools with QR codes"], answer: 0 },
  { id: 90, week: 9, question: "A limitation of MobiTangibles is:", options: ["It cannot function on wooden surfaces", "It may damage magnetic-sensitive objects like credit cards", "It needs no smartphone", "It cannot detect small magnets at close range"], answer: 1 },

  // ── WEEK 10 ──
  { id: 91, week: 10, question: "LLMs are primarily designed to:", options: ["Predict and generate language using large-scale training data", "Render 3D animations", "Compress multimedia files", "Control robotic hardware"], answer: 0 },
  { id: 92, week: 10, question: "Which of the following is an example of a multimodal input for an AI system?", options: ["Only typed text", "Text, image, or audio combined", "A Wi-Fi password", "A device serial number"], answer: 1 },
  { id: 93, week: 10, question: "What is the function of prompting in LLM interactions?", options: ["Debugging internal model weights", "Giving the model instructions or context to perform a task", "Measuring CPU temperature", "Optimizing internet bandwidth"], answer: 1 },
  { id: 94, week: 10, question: "Which is a key challenge in AI-based personalization?", options: ["Limited screen brightness", "Privacy concerns around user data", "High-fidelity UI design", "Lack of color contrast in icons"], answer: 1 },
  { id: 95, week: 10, question: "In behavior modeling, \"Effect\" refers to:", options: ["The color of the UI", "The user's actual response or action", "The predicted CPU usage", "The system's refresh rate"], answer: 1 },
  { id: 96, week: 10, question: "Zero-shot prompting allows the model to:", options: ["Produce outputs without being given examples", "Run without electricity", "Access private user data", "Train without GPUs"], answer: 0 },
  { id: 97, week: 10, question: "Which of these is a benefit of AI for accessibility?", options: ["Faster firmware updates", "Real-time speech-to-text for deaf users", "Higher download speeds", "Larger app icons"], answer: 1 },
  { id: 98, week: 10, question: "Behavior-optimized content refers to:", options: ["Messages crafted to trigger specific user reactions", "Code that compiles automatically", "Images compressed for mobile phones", "Deleted browsing history"], answer: 0 },
  { id: 99, week: 10, question: "Ethical concerns with LLMs include:", options: ["Keyboard layouts", "Bias, manipulation risk, and misinformation", "Slow Wi-Fi speed", "File naming conventions"], answer: 1 },
  { id: 100, week: 10, question: "An MLLM (Multimodal Large Language Model) improves HCI by:", options: ["Understanding and generating across multiple input/output formats", "Replacing all user research", "Removing the need for interfaces", "Turning apps into offline-only tools"], answer: 0 },

  // ── WEEK 11 ──
  { id: 101, week: 11, question: "Privacy in HCI refers to:", options: ["Users' ability to control their personal data", "Increasing app size", "Removing encryption from messages", "Designing only visual elements"], answer: 0 },
  { id: 102, week: 11, question: "Which of the following is an example of a security feature?", options: ["Dark themes", "Two-factor authentication (2FA)", "Changing wallpapers", "Offline advertisements"], answer: 1 },
  { id: 103, week: 11, question: "Deepfakes are created using:", options: ["Generative Adversarial Networks (GANs)", "Spreadsheet formulas", "Static HTML tags", "Audio compression tools"], answer: 0 },
  { id: 104, week: 11, question: "Which type of harm involves AI generating biased or unfair outcomes?", options: ["Bias and discrimination", "Increased RAM usage", "Reduced display brightness", "Slow keyboard response"], answer: 0 },
  { id: 105, week: 11, question: "A real-world example of privacy by design is:", options: ["WhatsApp's end-to-end encryption", "Phone ringtones", "Auto-rotate screen settings", "File naming conventions"], answer: 0 },
  { id: 106, week: 11, question: "One major risk of deepfakes is:", options: ["Creating propaganda or misinformation", "Improving audio quality", "Faster battery charging", "Removing the need for passwords"], answer: 0 },
  { id: 107, week: 11, question: "Security in HCI focuses on:", options: ["Protecting user data from unauthorized access", "Increasing the number of UI animations", "Designing only for children", "Removing all login screens"], answer: 0 },
  { id: 108, week: 11, question: "GDPR impacts HCI design by requiring:", options: ["Clear consent mechanisms and privacy transparency", "More emojis in interfaces", "Mandatory dark mode", "Faster loading animations"], answer: 0 },
  { id: 109, week: 11, question: "Which tool supports secure authentication?", options: ["Google Authenticator", "Stopwatch app", "Video filters", "Calculator app"], answer: 0 },
  { id: 110, week: 11, question: "A major challenge in privacy & security design is:", options: ["Balancing usability with strong protections", "Removing all security features entirely", "Hiding all system messages", "Making interfaces more confusing"], answer: 0 },

  // ── WEEK 12 ──
  { id: 111, week: 12, question: "Shannon's Level C focuses on:", options: ["Whether the received meaning achieves the intended effect", "Hardware choices", "Signal compression", "Gesture selection"], answer: 0 },
  { id: 112, week: 12, question: "In human communication, encoding means:", options: ["Choosing fonts", "Converting thoughts into words or symbols", "Measuring noise levels", "Compressing audio"], answer: 1 },
  { id: 113, week: 12, question: "A key feature of modern conversational AI is:", options: ["Natural Language Understanding", "Monochrome output", "Manual rule-writing", "Offline-only processing"], answer: 0 },
  { id: 114, week: 12, question: "An example of a conversational AI assistant is:", options: ["A calculator", "A stapler", "Google Assistant", "A desk lamp"], answer: 2 },
  { id: 115, week: 12, question: "A communication barrier includes:", options: ["Wallpapers", "Volume changes", "Extra brightness", "Semantic misunderstandings"], answer: 3 },
  { id: 116, week: 12, question: "AI conversational systems typically:", options: ["Only record audio", "Use NLP to interpret user messages", "Require physical switches", "Ignore user queries"], answer: 1 },
  { id: 117, week: 12, question: "A challenge in deploying conversational AI is:", options: ["Bias and misunderstanding nuanced input", "Limited font choices", "Keyboard shortcuts", "Battery drainage"], answer: 0 },
  { id: 118, week: 12, question: "Asimov's First Law states:", options: ["Robots must obey all commands", "Robots must protect themselves", "Robots may not harm humans or allow harm", "Robots must avoid emotions"], answer: 2 },
  { id: 119, week: 12, question: "Socially responsible MIAs aim to:", options: ["Compress images", "Promote fairness and inclusive interactions", "Reduce accessibility", "Avoid cultural sensitivity"], answer: 1 },
  { id: 120, week: 12, question: "A benefit of conversational AI in healthcare is:", options: ["Changing screen colors", "Increasing room volume", "Printing receipts", "Offering virtual guidance such as symptom checking"], answer: 3 },
];
